# Generated by Django 4.2.23 on 2025-08-08 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.defaults


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Designates whether this record should be treated as active",
                        verbose_name="is active",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="User biography/description.",
                        max_length=1000,
                        verbose_name="biography",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="User geographic location.",
                        max_length=100,
                        verbose_name="location",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("UTC", "UTC"),
                            ("Africa/Casablanca", "Casablanca"),
                            ("Africa/Johannesburg", "South Africa"),
                            ("America/New_York", "US Eastern"),
                            ("America/Chicago", "US Central"),
                            ("America/Denver", "US Mountain"),
                            ("America/Los_Angeles", "US Pacific"),
                            ("Europe/London", "London"),
                            ("Europe/Paris", "Paris"),
                            ("Europe/Berlin", "Berlin"),
                            ("Asia/Tokyo", "Tokyo"),
                            ("Asia/Shanghai", "Shanghai"),
                            ("Australia/Sydney", "Sydney"),
                        ],
                        default="UTC",
                        help_text="User timezone.",
                        max_length=50,
                        verbose_name="timezone",
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "Français"),
                            ("ar", "العربية"),
                        ],
                        default="en",
                        help_text="Language preference (ISO 639-1).",
                        max_length=10,
                        verbose_name="preferred language",
                    ),
                ),
                (
                    "privacy_level",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("friends", "Friends Only"),
                            ("private", "Private"),
                        ],
                        db_index=True,
                        default="public",
                        help_text="Privacy setting.",
                        max_length=20,
                        verbose_name="privacy level",
                    ),
                ),
                (
                    "notification_preferences",
                    models.JSONField(
                        default=core.defaults.get_default_notification_preferences,
                        help_text="Notification settings.",
                        verbose_name="notification preferences",
                    ),
                ),
                (
                    "theme_preference",
                    models.CharField(
                        choices=[
                            ("light", "Light Theme"),
                            ("dark", "Dark Theme"),
                            ("auto", "Auto (System)"),
                        ],
                        default="light",
                        help_text="UI theme preference.",
                        max_length=20,
                        verbose_name="theme preference",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Reference to User model.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "auth_user_profile",
                "indexes": [
                    models.Index(
                        fields=["user"], name="auth_user_p_user_id_054b27_idx"
                    ),
                    models.Index(
                        fields=["privacy_level"], name="auth_user_p_privacy_bf002a_idx"
                    ),
                ],
            },
        ),
    ]
